/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/kgWo7IM4Q0V
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function Footer() {
  return (
    (<footer className="w-full bg-gray-950 text-gray-50 py-12 md:py-16 lg:py-20">
      <div
        className="container flex flex-col md:flex-row justify-between items-start gap-8 md:gap-12">
        <div className="flex flex-col items-start gap-4">
          <div className="flex items-center gap-2">
            <img
              alt="Acme Inc. Logo"
              className="h-20 w-20"
              height={24}
              src="https://res.cloudinary.com/dgpxvazru/image/upload/v1714303824/Poultry/ellipse-1_2x_yzql1o.webp"
              style={{
                aspectRatio: "24/24",
                objectFit: "cover",
              }}
              width={24} />
            <span className="text-lg font-bold">Cartus agri Ltd.</span>
          </div>
          <p className="text-gray-400 max-w-[300px] sm:text-base lg:text-xl"> To produce healthy homegrown chicken for the population.</p>
          <div className="flex items-center gap-3">
            <span style={{color:'#d48e52'}} className=" hover:underline sm:text-base lg:text-xl" href="#">
              Get in touch with us
            </span>
          </div>
        </div>
        <div className="flex flex-col items-start gap-4">
          <div className="flex items-center gap-3">
            <LocateIcon className="h-5 w-5" />
            <div className="sm:text-base lg:text-xl">Kumasi</div>
          </div>
          <div className="flex items-center gap-3">
            <MailIcon className="h-5 w-5" />
            <Link className="sm:text-base lg:text-xl hover:underline" href="#">
              Mail Us
            </Link>
          </div>
          <div className="flex items-center gap-3">
            <PhoneIcon className="h-5 w-5" />
            <div className="sm:text-base lg:text-xl">+233 (0) 55836127</div>
          </div>
          <div className="flex items-center gap-3">
            <SmartphoneIcon className="h-5 w-5" />
            <div className="sm:text-base lg:text-xl">+233 (0) 543286970</div>
          </div>
        </div>
      </div>
    </footer>)
  );
}

function LocateIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="2" x2="5" y1="12" y2="12" />
      <line x1="19" x2="22" y1="12" y2="12" />
      <line x1="12" x2="12" y1="2" y2="5" />
      <line x1="12" x2="12" y1="19" y2="22" />
      <circle cx="12" cy="12" r="7" />
    </svg>)
  );
}


function MailIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>)
  );
}


function PhoneIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>)
  );
}


function SmartphoneIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="14" height="20" x="5" y="2" rx="2" ry="2" />
      <path d="M12 18h.01" />
    </svg>)
  );
}
