/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ph6XGuiiLZP
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"

export function Header() {
  return (
    (<header className="bg-[#8f2e37] flex justify-between items-center px-4 py-2 max-w-[1000px] mx-auto rounded-b-2xl h-[80px]">
      <div className="flex items-center">
        <img alt="Cartus Logo" className="h-12 mr-2" src="/placeholder.svg" />
        <div className="text-white">
          <div className="font-bold">CARTUS</div>
          <div className="text-xs">Quietly Brilliant</div>
        </div>
      </div>
      <div className="flex items-center space-x-8">
        <a className="flex items-center text-white space-x-2" href="#">
          <PhoneIcon className="h-6 w-6" />
          <span className="font-medium">055836127</span>
        </a>
        <a className="flex items-center text-white space-x-2" href="#">
          <MailboxIcon className="h-6 w-6" />
          <span className="font-medium">Mail Us</span>
        </a>
        <Link className="text-white block" href="#">
          Our Services
        </Link>
        <Link className="text-white block" href="#">
          Why Us
        </Link>
        <Link className="text-white block" href="#">
          About Us
        </Link>
      </div>
    </header>)
  );
}

function MailboxIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M22 17a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9.5C2 7 4 5 6.5 5H18c2.2 0 4 1.8 4 4v8Z" />
      <polyline points="15,9 18,9 18,11" />
      <path d="M6.5 5C9 5 11 7 11 9.5V17a2 2 0 0 1-2 2v0" />
      <line x1="6" x2="7" y1="10" y2="10" />
    </svg>)
  );
}


function PhoneIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>)
  );
}
