/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/SpsLdWyvZRF
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import styles from './Innovative.module.css';

export function Innovative() {
  return (
    <div className={styles.container}>
      <div className={styles.description}>
        <h2>
          Quality, innovation and food safety.
        </h2>
      </div>
      <div className={styles.info}>
        <h4>
          Welcome to our world of livestock expertise! Explore, learn, grow, and buy with us.
        </h4>
        <Link
          className={styles.link}
          href="#">
          Read more
        </Link>
      </div>
    </div>
  );
}
